export const ZONES_DATA = {
  'Épaule': {
    titre: `Pourquoi j'ai mal à l'épaule`,
    anatomie: `L'épaule est l'articulation la plus mobile de tout ton corps — c'est ce qui te permet de porter, pousser, tirer, attraper, lever les bras au-dessus de la tête. Cette mobilité a un prix : c'est une zone peu "protégée" structurellement, qui repose beaucoup sur les muscles et tendons autour pour rester stable. Résultat : c'est souvent la première à encaisser quand tu compenses ailleurs — une nuque raide, un dos qui ne suit plus, un stress qui se loge quelque part et remonte.`,
    symbolique: `Dans l'approche somatique, l'épaule est associée à la capacité de porter — au sens propre comme au figuré. "Porter le monde sur ses épaules", "avoir les épaules solides" pour dire qu'on est capable d'assumer, "épauler quelqu'un" quand on le soutient : le vocabulaire ne trompe pas. Une épaule qui se bloque, qui tire, qui devient douloureuse sans cause physique évidente, questionne souvent une charge — professionnelle, familiale, affective — qu'on porte depuis trop longtemps sans la poser, ou qu'on n'a même pas choisi de porter.\n\nCe n'est pas toujours une "grosse" charge. Parfois c'est une accumulation de petites responsabilités qu'on a fini par considérer comme normales — jusqu'à ce que le corps dise autre chose.`,
    gauche: `Ce que tu portes dans l'action — le travail, les décisions, ce que tu dois "assumer".`,
    droite: `Ce que tu portes pour les autres, dans le lien — l'affectif, ce que tu retiens pour ne pas peser sur quelqu'un.`,
    element: 'Bois',
    elementDescription: `L'élément de la structure et de la croissance. Un bois sain plie sans casser ; un bois trop rigide finit par se fissurer sous la charge.`,
    questions: [
      `Qu'est-ce que je porte, là, maintenant, dans ma vie ?`,
      `Est-ce que cette charge, je l'ai choisie — ou est-ce qu'elle s'est imposée à moi sans que je m'en rende compte ? Depuis quand est-ce que je porte ça ?`,
      `Si je posais cette charge, ne serait-ce qu'une minute, qu'est-ce que je ressentirais ? Du soulagement ? De la culpabilité ? De la peur ?`,
      `Qu'est-ce qui, en moi, pense que je dois porter ça — et est-ce que c'est encore vrai aujourd'hui ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur à l'épaule peut avoir plein de causes physiques (posture, surmenage, blessure) qui méritent d'être vues par un professionnel de santé — surtout si la douleur persiste, s'aggrave, ou s'accompagne d'une perte de mobilité. La lecture symbolique vient en complément, jamais à la place.`,
  },

  'Nuque': {
    titre: `Pourquoi j'ai mal à la nuque`,
    anatomie: `La nuque relie ta tête à ton corps — c'est le passage obligé entre ce que tu penses et ce que tu vis physiquement. Elle est mobile pour te permettre de regarder autour de toi, d'anticiper, de te tourner vers ce qui se passe. C'est aussi une zone très innervée et musculairement fine, donc particulièrement sensible au stress mental : quand la tête tourne à plein régime, c'est souvent la nuque qui trinque en premier.`,
    symbolique: `La nuque, dans l'approche somatique, est liée à la flexibilité — au sens propre (tourner la tête) comme au figuré (accepter de changer de point de vue, lâcher le contrôle). Une nuque raide questionne souvent une rigidité : "je ne veux pas voir les choses autrement", "je dois garder le contrôle", "je n'ai pas le droit de changer d'avis". C'est aussi la zone du regard qu'on porte sur les autres et sur soi-même — une nuque bloquée peut parler d'un refus de voir quelque chose, ou à l'inverse, de la peur de ce qu'on verrait si on se tournait vers ça.`,
    gauche: `Une rigidité liée au contrôle, à la difficulté de lâcher prise sur ce que tu diriges ou décides. "Je dois garder les yeux partout."`,
    droite: `Une rigidité liée à ce que tu refuses de voir dans une relation, ou à la difficulté d'accepter le regard des autres sur toi.`,
    element: 'Bois',
    elementDescription: `La flexibilité et la capacité à s'adapter sans casser. Une nuque raide dit souvent : je tiens une position depuis trop longtemps sans plier.`,
    questions: [
      `Qu'est-ce que je refuse de voir, en ce moment, dans ma vie ?`,
      `Y a-t-il une situation où je sais que j'ai raison — mais où je commence à douter que ce soit vraiment le cas ?`,
      `Si je me tournais vers ce que j'évite de regarder, qu'est-ce que je découvrirais ?`,
      `De quoi ai-je peur si je change d'avis maintenant — de perdre le contrôle, ou de perdre la face ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur à la nuque peut avoir des causes physiques variées (posture, stress musculaire, mauvaise literie) — et dans de rares cas, des signes qui nécessitent un avis médical rapide (douleur intense soudaine, fièvre, engourdissement dans les bras). En cas de doute, consulte un professionnel de santé.`,
  },

  'Dos': {
    titre: `Pourquoi j'ai mal au dos`,
    anatomie: `Le dos, c'est ta structure porteuse — la colonne qui te tient debout, qui encaisse ton poids, tes mouvements, tes efforts, à chaque instant de la journée. Il se divise en plusieurs zones (haut, milieu, bas) qui ne racontent pas exactement la même chose, mais dans l'ensemble, le dos est ce qui te permet de tenir droite face à ce que la vie te demande.`,
    symbolique: `"En avoir plein le dos", "avoir bon dos", "se sentir soutenu" ou au contraire "lâché" : le dos est la zone du soutien — celui qu'on reçoit, celui qu'on attend, celui qui manque. Une douleur dans le bas du dos questionne souvent le soutien matériel, financier, la sécurité de base ("est-ce que je me sens en sécurité dans ma vie en ce moment ?"). Une douleur dans le haut du dos, plus proche des épaules, revient vers la charge et les responsabilités. Le milieu du dos, lui, touche souvent à la culpabilité et à ce qu'on n'ose pas dire.\n\nLe dos, c'est aussi ce qu'on tourne : "tourner le dos à quelque chose", fuir une situation qu'on n'a pas envie d'affronter en face.`,
    gauche: `Le soutien lié à ce que tu construis, à ta sécurité matérielle, à ta capacité d'action. Une tension à gauche peut parler d'une inquiétude sur ta stabilité (travail, finances, projets).`,
    droite: `Le soutien qu'on attend des autres, le sentiment d'être (ou pas) épaulée dans une relation ou une situation affective.`,
    element: 'Eau',
    elementDescription: `Pour le bas du dos en particulier. Lié aux reins, à l'énergie vitale profonde, à la sécurité et à la peur. Une eau qui manque de fluidité peut se traduire par une rigidité dans le bas du dos ; une peur ancienne, non résolue, s'y loge souvent.`,
    questions: [
      `Est-ce que je me sens soutenue en ce moment, dans ma vie ?`,
      `Si je ne me sens pas soutenue, par qui ou par quoi j'aurais besoin de l'être — et est-ce que je l'ai déjà demandé ?`,
      `Y a-t-il une situation à laquelle je tourne le dos depuis un moment, plutôt que de l'affronter ?`,
      `Est-ce que je porte cette charge parce que personne d'autre ne peut la porter — ou parce que je n'ai jamais appris à la poser ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Le mal de dos est l'une des douleurs les plus fréquentes et a le plus souvent des causes physiques (posture, muscles, disques) qu'il vaut mieux faire évaluer par un professionnel de santé, surtout si la douleur est intense, irradie dans une jambe, ou s'accompagne d'engourdissements — ces signes méritent un avis médical rapide.`,
  },

  'Genou': {
    titre: `Pourquoi j'ai mal au genou`,
    anatomie: `Le genou est l'articulation qui te permet d'avancer, de plier, de t'arrêter, de changer de direction. Il absorbe une bonne partie du choc à chaque pas, chaque saut, chaque changement d'appui. C'est une articulation charnière — littéralement — entre ce qui est derrière toi (le passé, ce que tu as déjà parcouru) et ce qui est devant (où tu vas).`,
    symbolique: `Le genou est très souvent associé à l'avancement dans la vie — et à la résistance qu'on y met. "Plier le genou", "être à genoux" (soumission, épuisement), "avancer" ou au contraire "refuser d'avancer" : un genou douloureux questionne souvent une avancée qu'on freine, consciemment ou non. Ça peut être une peur du changement, une difficulté à accepter une nouvelle direction, ou à l'inverse une trop grande rigidité — refuser de plier, de céder, de s'adapter à ce qui se présente.\n\nC'est aussi la zone de l'ego et de l'orgueil dans certaines lectures : la difficulté à "plier" devant une situation, à admettre qu'on avait tort, ou à demander de l'aide.`,
    gauche: `La résistance liée à une décision à prendre, à un changement de direction professionnelle ou concrète que tu repousses.`,
    droite: `La résistance à avancer dans une relation, un deuil, une situation affective — accepter de tourner une page.`,
    element: 'Bois',
    elementDescription: `La croissance et la direction, comme une pousse qui doit savoir plier sous le vent sans se casser pour continuer à grandir.`,
    questions: [
      `Est-ce qu'il y a, en ce moment, une direction dans ma vie que j'hésite à prendre ?`,
      `Qu'est-ce qui m'empêche d'avancer là-dessus — une peur, un manque de clarté, ou une résistance à lâcher ce qui était avant ?`,
      `Si j'acceptais de "plier" sur ce point précis, qu'est-ce que ça voudrait dire pour moi ?`,
      `Est-ce que je résiste parce que la direction n'est vraiment pas la bonne — ou parce que changer me demande d'admettre que je me suis trompée avant ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur au genou peut avoir de nombreuses causes physiques (usure, blessure sportive, désalignement) qu'il vaut mieux faire évaluer par un professionnel de santé — surtout en cas de gonflement, de blocage articulaire, ou de douleur après un traumatisme.`,
  },

  'Cheville': {
    titre: `Pourquoi j'ai mal à la cheville`,
    anatomie: `La cheville est ta base d'appui — c'est elle qui absorbe et redistribue ton poids à chaque pas, qui s'ajuste au terrain, qui te stabilise. Petite articulation, grand rôle : c'est elle qui détermine si tu avances avec assurance ou si tu marches sur un terrain instable.`,
    symbolique: `La cheville est liée à la souplesse dans l'avancée — pas la direction elle-même (ça, c'est le genou), mais la façon dont tu t'ajustes en chemin. Une entorse ou une douleur récurrente à la cheville questionne souvent un manque de flexibilité face à l'imprévu : "je veux avancer, mais je refuse de dévier de mon plan", ou à l'inverse une peur de manquer d'appui, de stabilité, dans une période de changement. C'est aussi la zone du "terrain sous les pieds" — se sentir en équilibre, ou pas, dans une situation.`,
    gauche: `Le manque de stabilité ressenti dans l'action concrète — un projet, une décision, un changement de terrain professionnel.`,
    droite: `L'instabilité ressentie dans une relation ou une situation affective — se sentir sur un terrain mouvant avec quelqu'un.`,
    element: 'Bois',
    elementDescription: `La souplesse et l'ajustement. Une cheville qui se tord ou se raidit questionne ta capacité à t'adapter à un terrain qui change sans perdre l'équilibre.`,
    questions: [
      `Est-ce que je me sens stable, en ce moment, dans ma vie ?`,
      `Y a-t-il un imprévu récent que j'ai eu du mal à encaisser sans perdre pied ?`,
      `Est-ce que je m'accroche à un plan précis parce qu'il est le bon — ou parce que dévier me fait peur ?`,
      `Qu'est-ce qui se passerait si je lâchais un peu de contrôle sur "comment ça doit se passer" ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur à la cheville peut avoir des causes physiques variées (entorse, instabilité chronique, usure) qu'il vaut mieux faire évaluer par un professionnel de santé — surtout en cas de gonflement important, d'impossibilité de poser le pied, ou de douleur après un traumatisme.`,
  },

  'Cervicales': {
    titre: `Pourquoi j'ai mal aux cervicales`,
    anatomie: `Les cervicales sont les sept vertèbres du haut de ta colonne, celles qui soutiennent le poids de ta tête — environ 5 kg, en équilibre permanent. Contrairement à la nuque (les muscles autour), les cervicales, c'est la structure : l'os, l'architecture qui tient tout ça debout. Quand elles sont douloureuses ou comprimées, c'est souvent un poids réel, mécanique, qui s'est accumulé — parfois littéralement le poids d'une tête qu'on penche trop souvent vers un écran.`,
    symbolique: `Si la nuque parle de flexibilité et de regard, les cervicales parlent de charge mentale — le poids de ce qu'on pense, rumine, n'arrive pas à poser. "Se prendre la tête", "avoir la tête qui pèse", "ne plus savoir où donner de la tête" : les cervicales portent souvent une surcharge de pensées, de décisions à prendre, d'informations à traiter. C'est aussi une zone proche de la gorge — donc parfois liée à ce qu'on tait, à ce qu'on n'ose pas dire et qui reste coincé quelque part entre la tête et la voix.`,
    gauche: `Le poids mental lié à ce qu'il faut décider, organiser, gérer concrètement. Une surcharge de "choses à faire" dans la tête.`,
    droite: `Ce qu'on garde pour soi dans une relation, ce qu'on n'ose pas dire à quelqu'un par peur de la réaction ou du conflit.`,
    element: 'Bois',
    elementDescription: `Ici, moins la flexibilité que la capacité de l'arbre à porter le poids de sa propre cime sans plier.`,
    questions: [
      `Qu'est-ce qui tourne en boucle dans ma tête, en ce moment ?`,
      `Est-ce que c'est une charge de décisions à prendre, ou plutôt quelque chose que je n'ai pas dit et qui reste coincé ?`,
      `Depuis combien de temps est-ce que je porte ça dans ma tête sans le poser sur papier, ou le dire à quelqu'un ?`,
      `Qu'est-ce que je crains qu'il se passe si j'arrête, ne serait-ce qu'un instant, de tout penser en même temps ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur aux cervicales peut avoir des causes physiques sérieuses (compression, hernie, arthrose) et mérite un avis médical, surtout en cas d'engourdissement dans les bras, de maux de tête intenses, ou de vertiges associés.`,
  },

  'Hanche': {
    titre: `Pourquoi j'ai mal à la hanche`,
    anatomie: `La hanche est l'articulation qui relie ton tronc à tes jambes — c'est elle qui permet la marche, l'enjambée, le changement d'appui d'une jambe à l'autre. C'est une zone profonde, entourée de muscles puissants, mais aussi une des plus émotionnellement "chargées" du corps : c'est là que beaucoup de tensions liées au bassin, à la sexualité et à la sécurité viennent se loger.`,
    symbolique: `La hanche est souvent associée à l'avancée dans la vie au sens large — pas juste la direction (genou) ni l'ajustement au terrain (cheville), mais la capacité à avancer avec tout son poids, à s'engager pleinement dans un mouvement, une décision, une nouvelle étape de vie. C'est aussi une zone très liée à l'identité, à la féminité, à ce qu'on porte comme histoire familiale ou héritée. Une hanche bloquée questionne parfois : est-ce que je m'autorise à avancer pleinement, ou est-ce que je retiens quelque chose — une peur, un attachement au passé, une loyauté invisible envers quelqu'un ou quelque chose ?`,
    gauche: `La difficulté à s'engager pleinement dans une direction concrète — un projet, un changement de vie, une décision qui demande de "s'avancer" totalement.`,
    droite: `Ce qui retient dans la sphère relationnelle ou familiale — un attachement, une loyauté, une histoire héritée qui freine l'avancée.`,
    element: 'Terre',
    elementDescription: `L'ancrage, la sécurité, le nourrissage. Une terre trop rigide empêche d'avancer ; une terre instable empêche de se sentir en sécurité pour le faire.`,
    questions: [
      `Est-ce que je me sens pleinement engagée dans ma vie en ce moment, ou est-ce que je retiens quelque chose ?`,
      `Y a-t-il une étape que je repousse depuis longtemps parce qu'elle me demande de m'engager totalement ?`,
      `Est-ce que ce qui me retient m'appartient vraiment, ou est-ce que c'est une peur, une loyauté héritée de quelqu'un d'autre ?`,
      `Si je m'autorisais à avancer pleinement, qui ou quoi aurais-je l'impression de trahir ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur à la hanche peut avoir des causes physiques variées (arthrose, tendinite, désalignement) qu'il vaut mieux faire évaluer par un professionnel de santé — surtout en cas de douleur persistante, de perte de mobilité, ou de douleur nocturne.`,
  },

  'Poignet': {
    titre: `Pourquoi j'ai mal au poignet`,
    anatomie: `Le poignet est une articulation fine et complexe, à la jonction entre ta main et ton bras. C'est lui qui te permet de saisir, tenir, manipuler, écrire, créer. Beaucoup de petits os, beaucoup de tendons — une zone qui demande de la précision plus que de la force, et qui encaisse souvent les mouvements répétitifs sans qu'on y prête attention, jusqu'au jour où elle proteste.`,
    symbolique: `Le poignet est lié à la capacité de tenir et de lâcher — au sens propre (saisir un objet) comme au figuré (tenir une situation à bout de bras, ou au contraire refuser de lâcher prise). "Tenir bon", "avoir les mains liées", "ne plus savoir où donner de la main" : un poignet douloureux questionne souvent une situation qu'on retient trop fermement — un contrôle qu'on refuse de desserrer, une charge qu'on continue à "tenir à bout de bras" alors qu'elle épuise. C'est aussi la zone de l'exécution : contrairement à l'épaule (qui porte la charge globale), le poignet, c'est le détail, le geste précis, le "comment on fait concrètement".`,
    gauche: `Ce que tu tiens fermement dans le concret — un contrôle sur un projet, une tâche que tu ne délègues pas, une exécution que tu veux maîtriser jusqu'au détail.`,
    droite: `Ce que tu retiens dans une relation — une situation à laquelle tu t'accroches, une main que tu ne veux pas lâcher, même si elle te coûte de l'énergie.`,
    element: 'Métal',
    elementDescription: `La précision, la structure fine, et aussi le deuil et le lâcher-prise. Un métal trop rigide devient cassant.`,
    questions: [
      `Qu'est-ce que je tiens fermement en ce moment, sans vraiment me demander si je devrais ?`,
      `Est-ce que je tiens ça parce que c'est nécessaire, ou parce que lâcher me fait peur ?`,
      `Qu'est-ce qui se passerait, concrètement, si je desserrais un peu ma prise sur ça ?`,
      `Est-ce que je tiens cette situation — ou est-ce qu'elle me tient, moi ?`,
    ],
    avertissement: `Ceci n'est pas un diagnostic médical. Une douleur au poignet peut avoir des causes physiques variées (tendinite, syndrome du canal carpien, mouvement répétitif) qu'il vaut mieux faire évaluer par un professionnel de santé — surtout en cas d'engourdissement, de perte de force, ou de douleur qui persiste malgré le repos.`,
  },
}
